name: 'fci_dbt'
version: '1.0.0'

profile: 'fci_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  fci_dbt:
    colsubsidio:
      staging:
        +materialized: view
      marts:
        +materialized: table
    giz:
      staging:
        +materialized: view
        +schema: proyecto_giz
      marts:
        +materialized: table
        +schema: proyecto_giz