-- Grano: un registro del modulo Zoho (id).
-- Name conserva el documento como texto; los eventos no se deduplican por persona.
select
    id,
    nullif(trim(Name), '') as documento,
    safe_cast(`Created_Time` as timestamp) as created_time,
    trim(`Primer_nombre`) as primer_nombre,
    trim(`Segundo_nombre`) as segundo_nombre,
    trim(`Primer_apellido`) as primer_apellido,
    trim(`Segundo_apellido`) as segundo_apellido,
    date(safe_cast(`Fecha_de_nacimiento` as timestamp)) as fecha_de_nacimiento,
    safe_cast(`Edad` as int64) as edad,
    lower(trim(`Tipo_de_documento`)) as tipo_de_documento,
    trim(`N_mero_de_tel_fono_celular`) as n_mero_de_tel_fono_celular,
    lower(trim(`Nacionalidad`)) as nacionalidad,
    trim(`Otra_nacionalidad`) as otra_nacionalidad,
    lower(trim(`Modalidad_de_atenci_n`)) as modalidad_de_atenci_n,
    lower(trim(`Tipo_de_poblaci_n`)) as tipo_de_poblaci_n,
    trim(`Ruta_Mujer`) as ruta_mujer,
    lower(trim(`Preinscripci_n_completad`)) as preinscripci_n_completad,
    lower(trim(`Municipio_de_residencia1`)) as municipio_de_residencia1,
    lower(trim(`Municipio_de_nacimiento`)) as municipio_de_nacimiento,
    trim(`Otro_municipio_de_nacimiento`) as otro_municipio_de_nacimiento,
    lower(trim(`Departamento_de_nacimiento`)) as departamento_de_nacimiento,
    lower(trim(`Localidad`)) as localidad,
    trim(`Direcci_n_de_residencia`) as direcci_n_de_residencia,
    lower(trim(`Actualmente_te_encuentras`)) as actualmente_te_encuentras,
    lower(trim(`Nivel_educativo_alcanzado`)) as nivel_educativo_alcanzado,
    lower(trim(`Ha_tenido_empleo_con_caja_de_compensaci_n`)) as ha_tenido_empleo_con_caja_de_compensaci_n,
    trim(`A_os_totales_de_experiencia_laboral`) as a_os_totales_de_experiencia_laboral,
    lower(trim(`D_nde_te_enteraste_de_esta_vacante`)) as d_nde_te_enteraste_de_esta_vacante,
    trim(`Cu_l_de_nuestras_vacantes_llam_tu_atenci_n`) as cu_l_de_nuestras_vacantes_llam_tu_atenci_n,
    safe_cast(_loaded_at as timestamp) as _loaded_at,
    safe_cast(Modified_Time as timestamp) as modified_time
from {{ source('zoho_raw_ruta_mujer', 'pre_registro_rutam') }}
