-- Grano: un registro del modulo Zoho (id).
select
    id,
    nullif(trim(Name), '') as codigo_vacante,
    safe_cast(`Created_Time` as timestamp) as created_time,
    trim(`Nombre_vacante`) as nombre_vacante,
    safe_cast(`N_mero_de_puestos_de_trabajo` as int64) as n_mero_de_puestos_de_trabajo,
    lower(trim(`Tipo_de_contrato`)) as tipo_de_contrato,
    lower(trim(`Estado_de_la_vacante`)) as estado_de_la_vacante,
    lower(trim(`Ciudad_Municipio_de_la_vacante`)) as ciudad_municipio_de_la_vacante,
    lower(trim(`Departamento_de_la_vacante`)) as departamento_de_la_vacante,
    lower(trim(`Departamento`)) as departamento,
    lower(trim(`Municipio`)) as municipio,
    lower(trim(`Rango_salarial`)) as rango_salarial,
    safe_cast(`Tiempo_de_experiencia_requerido_meses` as int64) as tiempo_de_experiencia_requerido_meses,
    lower(trim(`Jornada_laboral`)) as jornada_laboral,
    trim(`Horario_de_trabajo`) as horario_de_trabajo,
    json_value(`Buscar_empresa`, '$.id') as buscar_empresa_id,
    json_value(`Buscar_empresa`, '$.name') as buscar_empresa_nombre,
    trim(`Nombre_de_la_empresa_1`) as nombre_de_la_empresa_1,
    trim(`Nombre_de_la_empresa`) as nombre_de_la_empresa,
    trim(`Ocupaci_n_CUOC_2`) as ocupaci_n_cuoc_2,
    trim(`Ocupaci_n_CUOC_3`) as ocupaci_n_cuoc_3,
    trim(`Email_de_Contacto`) as email_de_contacto,
    trim(`Nombre_de_contacto`) as nombre_de_contacto,
    date(safe_cast(`Fecha_de_inicio_de_la_vacante` as timestamp)) as fecha_de_inicio_de_la_vacante,
    date(safe_cast(`Fecha_final_de_la_vacante` as timestamp)) as fecha_final_de_la_vacante,
    lower(trim(`Posibilidad_de_trabajo_h_brido_remoto`)) as posibilidad_de_trabajo_h_brido_remoto,
    lower(trim(`Acepta_migrantes_regulares`)) as acepta_migrantes_regulares,
    safe_cast(_loaded_at as timestamp) as _loaded_at,
    safe_cast(Modified_Time as timestamp) as modified_time
from {{ source('zoho_raw_ruta_mujer', 'ge_vacantes_colsubsidios') }}
