-- Grano: un registro del modulo Zoho (id).
-- Name conserva el documento como texto; los eventos no se deduplican por persona.
select
    id,
    nullif(trim(Name), '') as documento,
    safe_cast(`Created_Time` as timestamp) as created_time,
    json_value(`Registro_Orientaci_n`, '$.id') as registro_orientaci_n_id,
    json_value(`Registro_Orientaci_n`, '$.name') as registro_orientaci_n_nombre,
    trim(`Primer_nombre`) as primer_nombre,
    trim(`Segundo_nombre`) as segundo_nombre,
    trim(`Primer_apellido`) as primer_apellido,
    trim(`Segundo_apellido`) as segundo_apellido,
    date(safe_cast(`Fecha_de_nacimiento` as timestamp)) as fecha_de_nacimiento,
    lower(trim(`Acompa_amiento_Psicosocial_Completado`)) as acompa_amiento_psicosocial_completado,
    lower(trim(`Estado_actual_del_proceso`)) as estado_actual_del_proceso,
    trim(`Concepto_de_orientaci_n`) as concepto_de_orientaci_n,
    lower(trim(`Nivel_de_necesidad_de_acompa_amiento_psicosocial`)) as nivel_de_necesidad_de_acompa_amiento_psicosocial,
    lower(trim(`Nivel_de_riesgo_psicosocial_identificado`)) as nivel_de_riesgo_psicosocial_identificado,
    trim(`Salud_mental`) as salud_mental,
    trim(`Gestor_Operativo`) as gestor_operativo,
    lower(trim(`Municipio_de_residencia`)) as municipio_de_residencia,
    lower(trim(`Localidad`)) as localidad,
    lower(trim(`Seleccione_el_tipo_de_barrera`)) as seleccione_el_tipo_de_barrera,
    trim(`Estrategia_para_la_superaci_n_de_la_barrera`) as estrategia_para_la_superaci_n_de_la_barrera,
    lower(trim(`Cuenta_con_una_segunda_barrera`)) as cuenta_con_una_segunda_barrera,
    lower(trim(`Seleccione_el_tipo_de_barrera_2`)) as seleccione_el_tipo_de_barrera_2,
    trim(`Estrategia_para_la_superaci_n_de_la_barrera_2`) as estrategia_para_la_superaci_n_de_la_barrera_2,
    lower(trim(`Cuenta_con_una_tercera_barrera`)) as cuenta_con_una_tercera_barrera,
    lower(trim(`Seleccione_el_tipo_de_barrera_3`)) as seleccione_el_tipo_de_barrera_3,
    trim(`Estrategia_para_la_superaci_n_de_la_barrera_3`) as estrategia_para_la_superaci_n_de_la_barrera_3,
    lower(trim(`Tipificaci_n_Mujer`)) as tipificaci_n_mujer,
    safe_cast(_loaded_at as timestamp) as _loaded_at,
    safe_cast(Modified_Time as timestamp) as modified_time,
    trim(`Evoluci_n`) as evoluci_n,
from {{ source('zoho_raw_ruta_mujer', 'psicosocial_rutam') }}
