-- Grano: un registro del modulo Zoho (id).
-- Name conserva el documento como texto; los eventos no se deduplican por persona.
select
    id,
    nullif(trim(Name), '') as documento,
    safe_cast(`Created_Time` as timestamp) as created_time,
    json_value(`Inscripci_n_RutaM`, '$.id') as inscripci_n_rutam_id,
    json_value(`Inscripci_n_RutaM`, '$.name') as inscripci_n_rutam_nombre,
    json_value(`Psicosocial_RutaM`, '$.id') as psicosocial_rutam_id,
    json_value(`Psicosocial_RutaM`, '$.name') as psicosocial_rutam_nombre,
    trim(`Primer_nombre`) as primer_nombre,
    trim(`Segundo_nombre`) as segundo_nombre,
    trim(`Primer_apellido`) as primer_apellido,
    trim(`Segundo_apellido`) as segundo_apellido,
    lower(trim(`Tipo_de_documento`)) as tipo_de_documento,
    safe_cast(`Edad` as int64) as edad,
    trim(`N_mero_de_Celular_principal`) as n_mero_de_celular_principal,
    date(safe_cast(`Fecha_de_Vinculaci_n_Laboral` as timestamp)) as fecha_de_vinculaci_n_laboral,
    lower(trim(`Mes_de_Colocaci_n`)) as mes_de_colocaci_n,
    trim(`Cargo_en_la_empresa`) as cargo_en_la_empresa,
    trim(`Nombre_de_empresa_contratante_empleador`) as nombre_de_empresa_contratante_empleador,
    trim(`NIT_de_empresa_contratante_empleador`) as nit_de_empresa_contratante_empleador,
    lower(trim(`Sector_econ_mico_empresa_contratante_empleador`)) as sector_econ_mico_empresa_contratante_empleador,
    lower(trim(`Tipo_de_contrato`)) as tipo_de_contrato,
    lower(trim(`Tipo_de_Empleo`)) as tipo_de_empleo,
    lower(trim(`Rango_salarial`)) as rango_salarial,
    safe_cast(`Salario_despu_s_de_la_Colocaci_n` as numeric) as salario_despu_s_de_la_colocaci_n,
    json_value(`Codigo_de_la_vacante`, '$.id') as codigo_de_la_vacante_id,
    json_value(`Codigo_de_la_vacante`, '$.name') as codigo_de_la_vacante_nombre,
    json_value(`Orientaci_n`, '$.id') as orientaci_n_id,
    json_value(`Orientaci_n`, '$.name') as orientaci_n_nombre,
    trim(`Gestor_Operativo`) as gestor_operativo,
    lower(trim(`Estado_de_mitigaci_n`)) as estado_de_mitigaci_n,
    lower(trim(`Nivel_de_mitigaci_n`)) as nivel_de_mitigaci_n,
    trim(`Categorizaci_n_de_Empleo_Verde`) as categorizaci_n_de_empleo_verde,
    lower(trim(`Es_un_empleo_con_titulo_de_educacion_superior`)) as es_un_empleo_con_titulo_de_educacion_superior,
    lower(trim(`Corte`)) as corte,
    safe_cast(_loaded_at as timestamp) as _loaded_at,
    safe_cast(Modified_Time as timestamp) as modified_time
from {{ source('zoho_raw_ruta_mujer', 'colocaci_n_colsubsidios') }}
