-- Grano: un registro del modulo Zoho (id).
-- Name conserva el documento como texto; los eventos no se deduplican por persona.
select
    id,
    nullif(trim(Name), '') as documento,
    json_value(`Owner`, '$.id') as owner_id,
    json_value(`Owner`, '$.name') as owner_nombre,
    trim(`Email`) as email,
    safe_cast(`Created_Time` as timestamp) as created_time,
    safe_cast(`Last_Activity_Time` as timestamp) as last_activity_time,
    trim(`Observaci_n_Calidad`) as observaci_n_calidad,
    date(safe_cast(`Fecha_intermediaci_n` as timestamp)) as fecha_intermediaci_n,
    trim(`Concepto_de_intermediaci_n`) as concepto_de_intermediaci_n,
    json_value(`Buscar_Vacante`, '$.id') as buscar_vacante_id,
    json_value(`Buscar_Vacante`, '$.name') as buscar_vacante_nombre,
    lower(trim(`Intermediaci_n_completada`)) as intermediaci_n_completada,
    trim(`Validaci_n_Calidad`) as validaci_n_calidad,
    trim(`Nombre_vacante`) as nombre_vacante,
    trim(`Nit_de_la_empresa`) as nit_de_la_empresa,
    trim(`Nombre_de_la_empresa_1`) as nombre_de_la_empresa_1,
    trim(`N_mero_de_celular`) as n_mero_de_celular,
    json_value(`Buscar_documento`, '$.id') as buscar_documento_id,
    json_value(`Buscar_documento`, '$.name') as buscar_documento_nombre,
    trim(`Primer_nombre`) as primer_nombre,
    trim(`Segundo_nombre`) as segundo_nombre,
    trim(`Concepto_de_Orientaci_n`) as concepto_de_orientaci_n,
    trim(`Primer_apellido`) as primer_apellido,
    trim(`Segundo_apellido`) as segundo_apellido,
    lower(trim(`Estado`)) as estado,
    date(safe_cast(`Fecha_de_orientaci_n` as timestamp)) as fecha_de_orientaci_n,
    trim(`Intermediador`) as intermediador,
    trim(`Novedad_Intermediaci_n`) as novedad_intermediaci_n,
    trim(`Perfil_ocupacional`) as perfil_ocupacional,
    lower(trim(`Corte`)) as corte,
    safe_cast(_loaded_at as timestamp) as _loaded_at,
    safe_cast(Modified_Time as timestamp) as modified_time
from {{ source('zoho_raw_ruta_mujer', 'intermediaci_n_ruta_m') }}
